services:
    email-api:
      container_name: email-api
      image: jonnattangc/emailservice:1.0.2
      restart: none
      #volumes:
      #  - ./app:/home/jonnattan/app
      ports:
        - "8070:8070"
      env_file:
        - ../envs/email_api.env
      networks:
        - db-net
      #command: tail -f /home/jonnattan/requirements.txt
networks:
  db-net:
